### ISSUE TITLE
Not enough STUN servers available.

### ISSUE THREAD

**Issue by fatinghenji** [MikeWang000000/Natter#21]
```python
➜  Natter git:(v0.9) python natter.py --check-nat
[INFO] - Getting STUN server IP...
[INFO] - NAT Type for UDP: [ Full cone (NAT 1) ]
[INFO] - Checking NAT Type for TCP...
Traceback (most recent call last):
  File "natter.py", line 969, in <module>
    main()
  File "natter.py", line 944, in main
    print_nat(src_host, src_port)
  File "natter.py", line 883, in print_nat
    if stun_client.is_tcp_cone():
  File "natter.py", line 401, in is_tcp_cone
    raise Exception("Not enough STUN servers available.")
Exception: Not enough STUN servers available.
```

**Comment by MikeWang000000** [comment]
检查 `natter-config.json`，并测试 STUN 服务器是否可用。
Natter 需要至少两个可用的 TCP STUN 服务器以检测 TCP NAT 类型。
