### ISSUE TITLE
windows10使用的时候报错

### ISSUE THREAD

**Issue by Timozaici** [MikeWang000000/Natter#23]
C:\Users\admin\Desktop>python natter.py -t 3389
[INFO] - Getting STUN server IP...
Traceback (most recent call last):
  File "C:\Users\admin\Desktop\natter.py", line 583, in <module>
    main()
  File "C:\Users\admin\Desktop\natter.py", line 574, in main
    natter = Natter(src_host, src_port, test_http=test_http, log_level=log_level)
  File "C:\Users\admin\Desktop\natter.py", line 427, in __init__
    self.keep_alive_sock = self._init_keep_alive_sock()
  File "C:\Users\admin\Desktop\natter.py", line 436, in _init_keep_alive_sock
    s.bind((self.source_ip, self.source_port))
OSError: [WinError 10013] 以一种访问权限不允许的方式做了一个访问套接字的尝试。

C:\Users\admin\Desktop>

**Comment by MikeWang000000** [comment]
如果您在Windows打开了3389远程桌面，该端口是独占的，因此Natter不能使用这个端口。
请使用其他未被占用的端口进行测试。

**Comment by Timozaici** [comment]
> 如果您在Windows打开了3389远程桌面，该端口是独占的，因此Natter不能使用这个端口。 请使用其他未被占用的端口进行测试。

原来是这样，谢谢解答

**Comment by WuJoker** [comment]
@MikeWang000000 如果在这种情况下，例如一台电脑是通过直接拨号获得运营商100开头IP（Full Cone），是不是永远无法使用工具了，3389必然是被占用的。
而借助一层路由器，例如把电脑的3389映射到路由器的13389，却可以通过python natter.py -t 13389获得穿透？

**Comment by MikeWang000000** [comment]
@WuJoker 转发可以在任意Full Cone的主机上进行，使用路由器是因为比较方便。
Windows上可以使用socat、gost等工具进行转发，监听Natter绑定的端口转发至3389*。
这种转发的缺陷是：由于它们都是是socket层面的转发，从3389端口看，外部连接的IP都是127.0.0.1。而Linux的iptables转发没有这种问题。

---

*注：和RDP服务监听的3389不同，Natter绑定的端口不是独占的，因此可以被其他工具转发至独占的目标端口。示意图为：
```
[100.64.1.1:3389] <-Port Forwarding-> [100.64.1.1:3456] <-Natter-> [203.0.113.10:14500]
```

**Comment by haitao9491** [comment]
> @WuJoker 转发可以在任意Full Cone的主机上进行，使用路由器是因为比较方便。 Windows上可以使用socat、gost等工具进行转发，监听Natter绑定的端口转发至3389*。 这种转发的缺陷是：由于它们都是是socket层面的转发，从3389端口看，外部连接的IP都是127.0.0.1。而Linux的iptables转发没有这种问题。
> 
> *注：和RDP服务监听的3389不同，Natter绑定的端口不是独占的，因此可以被其他工具转发至独占的目标端口。示意图为：
> 
> ```
> [100.64.1.1:3389] <-Port Forwarding-> [100.64.1.1:3456] <-Natter-> [203.0.113.10:14500]
> ```

windows10，Python 3.11.4环境下，使用v0.9的版本，端口转发成功，但存在以下几个问题：
1、运行时报错
2、端口转发成功，但端口老化问题严重，超过10分钟无连接端口便会失效，除非一直处于连接状态。但实际应用中明显不可能
[INFO] - Getting STUN server IP...
[INFO] - >>> [TCP] ('192.168.223.76', 8000) -> ('123.139.55.114', 24311) <<<
[INFO] - >>> [TCP] ('192.168.223.76', 8001) -> ('123.139.55.114', 24312) <<<
[INFO] - >>> [TCP] ('192.168.223.76', 10286) -> ('123.139.55.114', 24313) <<<
[INFO] - >>> [TCP] ('192.168.223.76', 10088) -> ('123.139.55.114', 24314) <<<
[INFO] - >>> [TCP] ('192.168.223.76', 10080) -> ('123.139.55.114', 24315) <<<
[INFO] - >>> [TCP] ('192.168.223.76', 55131) -> ('123.139.55.114', 24316) <<<
Traceback (most recent call last):
  File "C:\Users\ADMINI~1\Roaming\Intel\Natter-0.9\CMD_PO~1\..\natter.py", line 969, in <module>
    main()
  File "C:\Users\ADMINI~1\Roaming\Intel\Natter-0.9\CMD_PO~1\..\natter.py", line 960, in main
    natter.run()
  File "C:\Users\ADMINI~1\Roaming\Intel\Natter-0.9\CMD_PO~1\..\natter.py", line 794, in run
    self._update_status(nr)
  File "C:\Users\ADMINI~1\Roaming\Intel\Natter-0.9\CMD_PO~1\..\natter.py", line 763, in _update_status
    mapping = nr.get_mapping()
              ^^^^^^^^^^^^^^^^
  File "C:\Users\ADMINI~1\Roaming\Intel\Natter-0.9\CMD_PO~1\..\natter.py", line 683, in get_mapping
    self.stop_forward()
  File "C:\Users\ADMINI~1\Roaming\Intel\Natter-0.9\CMD_PO~1\..\natter.py", line 700, in stop_forward
    self.forwarder.stop()
  File "C:\Users\ADMINI~1\Roaming\Intel\Natter-0.9\CMD_PO~1\..\natter.py", line 575, in stop
    sock.sendto(b"", self.listen_addr)
OSError: [WinError 10049] 在其上下文中，该请求的地址无效。
Blat v3.2.22 (build : Jul 19 2019 23:25:36)
32-bit Windows, Full, Unicode

**Comment by MikeWang000000** [comment]
v0.9 是临时实验版本，转发多个端口时会出现不稳定的问题。
考虑到此问题，v2.0 系列改为单个实例只对应负责单个端口的转发，老化问题得以缓解。可以尝试使用最新版本测试。
