### ISSUE TITLE
v0.9版本报错

### ISSUE THREAD

**Issue by xiaotian2333** [MikeWang000000/Natter#31]
系统：win server 2012 r2 64位
python：3.1.1.4
已启用DMZ主机

日志如下
``` log
[INFO] - Getting STUN server IP...
[DEBUG] - Resolving hostname [fwa.lifesizecloud.com]...
[DEBUG] - Resolving hostname [stun.isp.net.au]...
[DEBUG] - Resolving hostname [stun.freeswitch.org]...
[DEBUG] - Resolving hostname [stun.voip.blackberry.com]...
[DEBUG] - Resolving hostname [stun.nextcloud.com]...
[DEBUG] - Resolving hostname [stun.stunprotocol.org]...
[DEBUG] - Resolving hostname [stun.sipnet.com]...
[DEBUG] - Resolving hostname [stun.radiojar.com]...
[DEBUG] - Resolving hostname [stun.sonetel.com]...
[DEBUG] - Resolving hostname [stun.voipgate.com]...
[DEBUG] - Resolving hostname [stun.miwifi.com]...
[DEBUG] - Resolving hostname [stun.qq.com]...
[DEBUG] - [Mon Aug 21 14:09:56 2023] Keep-Alive OK!
[DEBUG] - [Mon Aug 21 14:09:56 2023] Keep-Alive OK!
[DEBUG] - [Mon Aug 21 14:09:56 2023] Keep-Alive OK!
[DEBUG] - [Mon Aug 21 14:09:56 2023] Keep-Alive OK!
[DEBUG] - Trying TCP STUN: 52.221.199.123
[DEBUG] - (TCP) 52.221.199.123 says: ('120.230.61.243', 1200)
[INFO] - >>> [TCP] ('192.168.123.105', 3456) -> ('120.230.61.243', 1200) <<<
[DEBUG] - [Mon Aug 21 14:09:56 2023] Keep-Alive OK!
[DEBUG] - Trying UDP STUN: 111.206.174.2 (change ip:0/port:0)
[DEBUG] - (UDP) ('111.206.174.2', 3478) says: ('120.230.61.243', 1201)
[INFO] - >>> [UDP] ('0.0.0.0', 3456) -> ('120.230.61.243', 1201) <<<
[DEBUG] - [Mon Aug 21 14:09:56 2023] Keep-Alive OK!
[DEBUG] - Trying TCP STUN: 52.221.199.123
[DEBUG] - (TCP) 52.221.199.123 says: ('120.230.61.243', 1036)
[INFO] - >>> [TCP] ('127.0.0.1', 80) -> ('120.230.61.243', 1036) <<<
[DEBUG] - [Mon Aug 21 14:09:56 2023] Keep-Alive OK!
Traceback (most recent call last):
  File "C:\Program Files\upnp打洞\natter.py", line 969, in <module>
    main()
  File "C:\Program Files\upnp打洞\natter.py", line 960, in main
    natter.run()
  File "C:\Program Files\upnp打洞\natter.py", line 794, in run
    self._update_status(nr)
  File "C:\Program Files\upnp打洞\natter.py", line 763, in _update_status
    mapping = nr.get_mapping()
              ^^^^^^^^^^^^^^^^
  File "C:\Program Files\upnp打洞\natter.py", line 683, in get_mapping
    self.stop_forward()
  File "C:\Program Files\upnp打洞\natter.py", line 700, in stop_forward
    self.forwarder.stop()
  File "C:\Program Files\upnp打洞\natter.py", line 575, in stop
    sock.sendto(b"", self.listen_addr)
OSError: [WinError 10049] 在其上下文中，该请求的地址无效。
```

配置文件为
``` json
{
    "logging": {
        "level": "debug",
        "log_file": ""
    },
    "status_report": {
        "hook": "",
        "status_file": ""
    },
    "open_port": {
        "tcp": [
            "0.0.0.0:3456"
        ],
        "udp": [
            "0.0.0.0:3456"
        ]
    },
    "forward_port": {
        "tcp": [
            "127.0.0.1:80"
        ],
        "udp": [
            "127.0.0.1:53"
        ]
    },
    "stun_server": {
        "tcp": [
            "fwa.lifesizecloud.com",
            "stun.isp.net.au",
            "stun.freeswitch.org",
            "stun.voip.blackberry.com",
            "stun.nextcloud.com",
            "stun.stunprotocol.org",
            "stun.sipnet.com",
            "stun.radiojar.com",
            "stun.sonetel.com",
            "stun.voipgate.com"
        ],
        "udp": [
            "stun.miwifi.com",
            "stun.qq.com"
        ]
    },
    "keep_alive": "www.qq.com"
}
````

**Comment by MikeWang000000** [comment]
先前版本对 Windows 的处理没那么好，可以尝试一下最新的 v2 版本
