### ISSUE TITLE
GOST v3 适配：版本号匹配失败

### ISSUE THREAD

**Issue by MikeWang000000** [MikeWang000000/Natter#40]
当前仅支持 GOST v2，GOST v3 版本号匹配失败：
```
~ # natter.py -m gost -v
2024-01-20 19:04:30 [I] Natter v2.0.0-dev
Traceback (most recent call last):
  File "/usr/bin/natter.py", line 1483, in <module>
    main()
  File "/usr/bin/natter.py", line 1474, in main
    natter_main(show_title)
  File "/usr/bin/natter.py", line 1348, in natter_main
    forwarder = ForwardImpl()
                ^^^^^^^^^^^^^
  File "/usr/bin/natter.py", line 810, in __init__
    raise OSError("gost >= %s not available" % str(self.min_ver))
OSError: gost >= (2, 3) not available
~ # gost -V
gost v3.0.0-nightly.20240118 (go1.21.5 linux/amd64)
~ # 
```

**Comment by MikeWang000000** [comment]
Fixed by 4097219.
